### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by taschenbach** [bfidatadigipres/checksum_scripts#1]
Starting in line 122 of file checksum_speed_test.py
` # CRC32 Speed tests 65536 start here
            crc_time = timeit.timeit(lambda: crc_65536(filepath), number=1)
            print("It took {} seconds to retrieve the CRC32 65536 hash".format(crc2_time))
            print("Beginning the MD5 65536 speed test checks for your file")
            # MD5 Speed tests 65536 start here
            md5_time = timeit.timeit(lambda: md5_65536(filepath), number=1)`

crc_time should be crc2_time
md5_time should be md52_time

**Comment by digitensions** [comment]
Hey, thank you for spotting this, corrected [here](https://github.com/bfidatadigipres/checksum_scripts/commit/b0714d95236642e848d32595e4e47c2d7d80d664) And thanks for being my first Issue!
